apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginStackEdit
spec:
  enabled: true
  version: 1.0.0
  requires: "*"
  author:
    name: Halo OSS Team
    website: https://github.com/halo-dev
  logo: logo.svg
  homepage: https://github.com/halo-sigs/plugin-stackedit
  displayName: "StackEdit"
  description: "StackEdit 是一款开源的在线 Markdown 编辑器，支持实时预览。"
  license:
    - name: "GPL V3"
